version: "3"

services:
  finra-q1:
    build:
      context: Dockers/FINRA/Hive
    environment:
      - JAVA_HOME=/usr/lib/jvm/java
      - MAVEN_HOME=/usr/share/maven
    volumes:
      - .:/project
    entrypoint: /project/Dockers/FINRA/Hive/run_q1.sh
    depends_on:
      - hive-server
      - namenode
      - datanode
      - hive-metastore
      - hive-metastore-postgresql
      - presto-coordinator

  finra-q2:
    build:
      context: Dockers/FINRA/Hive
    environment:
      - JAVA_HOME=/usr/lib/jvm/java
      - MAVEN_HOME=/usr/share/maven
    volumes:
      - .:/project
    entrypoint: /project/Dockers/FINRA/Hive/run_q2.sh
    depends_on:
      - hive-server
      - namenode
      - datanode
      - hive-metastore
      - hive-metastore-postgresql
      - presto-coordinator

  finra-q3:
    build:
      context: Dockers/FINRA/Python
    volumes:
      - .:/project      
    entrypoint: ["python", "/project/actors.py", "/project/actors.csv"]

  finra-q4:
    build:
      context: Dockers/FINRA/Python
    volumes:
      - .:/project      
    entrypoint: ["python", "/project/arcade.py", "/project/arcade.csv"]

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ./fred-hive:/fred-hive
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    ports:
      - "8080:8080"

volumes:
  namenode:
  datanode:
